name: CI Learning

on:
  push: 
    branches:
      - main

jobs: 
  build: 

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: yarn install
      run: yarn install
    - name: eslint
      run: yarn lint:fix
    - name: prettier
      run: yarn format
    - name: tests
      run: yarn test
    - name: cypress tests
      uses: cypress-io/github-action@v5
      with:
        build: yarn build
        start: yarn start
        run: yarn cy:test